theme: jekyll-theme-cayman
title: Stato COVID-19 Italia Android
description: Progetto Open Source relativo alla realizzazione di una App Android per il monitoraggio della diffusione del virus in Italia :smiley:
