
name: Android Build & Release

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Android Builder
        uses: b4s36t4/Android-Action@0.0.1
